name: Build Debian Package

on:
  push:
    branches:
      - main  # 监听 main 分支的推送
    tags:
      - 'v*.*.*'  # 监听以 v 开头的标签，例如 v1.0.0
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 安装构建依赖
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y devscripts build-essential fakeroot lintian dpkg

      # 3. 构建 Debian 包
      - name: Build the Debian package
        run: |
          make deb  # 假设你的 Makefile 中有一个名为 deb 的目标来构建 .deb 包

      # 4. 查找生成的 .deb 文件
      - name: Find built .deb packages
        id: find_deb
        run: |
          deb_path=$(find . -maxdepth 1 -type f -name "*.deb" | tr '\n' ' ')
          echo "deb_path=$deb_path" >> $GITHUB_ENV

      # 5. 上传 Debian 包作为构建产物
      - name: Upload Debian package as artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: debian-package
          path: ${{ env.deb_path }}

      # 6. 使用 lintian 检查 Debian 包
      - name: Lint the Debian package
        run: |
          for deb in $deb_path; do
            lintian "$deb"
          done

      # 7. 创建 GitHub Release（仅在推送标签时触发）
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.deb_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
