name: CI

on:
  push:
    branches:
      - main
      - "release/*"
  pull_request:
    branches:
      - main

env:
  THEOS_REPO: https://github.com/theos/theos
  SDKS_REPO: https://github.com/theos/sdks
  CACHE_DIR: theos

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node: [14.x, 16.x] # 示例：支持多版本 Node.js，如果适用
        include:
          - project: default

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up environment variables
        run: |
          echo "upstream_heads=$(git ls-remote $THEOS_REPO | head -n 1 | cut -f 1)-$(git ls-remote $SDKS_REPO | head -n 1 | cut -f 1)" >> $GITHUB_ENV

      - name: Restore cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/$CACHE_DIR
          key: ${{ runner.os }}-theos-${{ env.upstream_heads }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          # 根据项目需要安装依赖，例如：
          brew install theos
          # 或其他依赖安装命令

      - name: Set up Theos
        uses: Randomblock1/theos-action@main
        with:
          theos_path: ${{ github.workspace }}/$CACHE_DIR

      - name: Build package
        run: |
          rm -f packages/*
          make package FINALPACKAGE=1
          make package THEOS_PACKAGE_SCHEME=rootless FINALPACKAGE=1

      - name: Upload Deb packages
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: DebPackages
          path: packages/*.deb

      - name: Upload Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: BuildLogs
          path: logs/*.log

      - name: Notify on Failure
        if: failure()
        uses: some-notification-action@v1
        with:
          message: "Build failed for `${{ github.repository }}` on `${{ github.ref }}`."

